# Generated by Django 4.2.3 on 2023-09-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0004_task_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('High', 'H'), ('Medium', 'M'), ('Low', 'L')], max_length=10),
        ),
    ]
