# Generated by Django 4.2.3 on 2023-09-26 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0005_alter_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_completed',
        ),
    ]
