# Generated by Django 4.2.3 on 2023-09-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0009_alter_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
