# Generated by Django 4.2.3 on 2023-08-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_bid_bid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_closed',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
