# Generated by Django 4.2.3 on 2023-08-22 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='winner',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
