# Generated by Django 4.2.3 on 2023-08-22 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='winner',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
