# Generated by Django 4.2.3 on 2023-08-22 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_listing_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, default=9.08, max_digits=20),
            preserve_default=False,
        ),
    ]
