# Generated by Django 4.2.3 on 2023-08-22 05:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_listing_starting_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
