# Generated by Django 4.2.3 on 2023-09-04 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post_likes_follower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='follower',
            new_name='who_follows',
        ),
        migrations.RenameField(
            model_name='follower',
            old_name='following',
            new_name='who_is_followed',
        ),
    ]
