# Generated by Django 4.2.3 on 2023-09-04 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_rename_follower_follower_who_follows_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='who_follows',
            new_name='follower',
        ),
        migrations.RenameField(
            model_name='follower',
            old_name='who_is_followed',
            new_name='following',
        ),
    ]
